// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/lyricapp/lyric/web/internal/web/data"

func Search() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"space-y-2\"><h1 class=\"text-4xl font-bold\">Search</h1><p class=\"text-base-content/70 text-lg\">Find tracks, artists, and albums for your next set.</p></section><section class=\"space-y-4 rounded-box bg-base-100 p-6 shadow-sm\"><div class=\"join w-full\"><span class=\"join-item btn btn-ghost btn-square\" aria-hidden=\"true\">🔍</span> <input id=\"search-input\" type=\"search\" placeholder=\"Search songs, artists, or albums\" class=\"input join-item input-bordered w-full\" autocomplete=\"off\"> <button id=\"clear-search\" type=\"button\" class=\"join-item btn btn-ghost hidden\">Clear</button></div><div><span class=\"text-sm font-semibold uppercase tracking-wide text-base-content/60\">Filter by language</span><div class=\"mt-3 flex flex-wrap gap-2\" id=\"language-filter\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, lang := range data.FilterLanguages {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button type=\"button\" class=\"badge badge-outline cursor-pointer px-4 py-3 text-sm\" data-lang=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(lang)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/components/search.templ`, Line: 34, Col: 105}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" aria-pressed=\"false\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(lang)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/components/search.templ`, Line: 34, Col: 135}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div></section><section class=\"space-y-6 rounded-box bg-base-100 p-6 shadow-sm\"><div class=\"flex flex-wrap items-center justify-between gap-4\"><div class=\"tabs tabs-boxed bg-base-200 p-1\" role=\"tablist\"><button type=\"button\" class=\"tab tab-lifted px-4 py-2\" data-tab=\"tracks\" role=\"tab\" aria-selected=\"true\">Tracks</button> <button type=\"button\" class=\"tab tab-lifted px-4 py-2\" data-tab=\"albums\" role=\"tab\" aria-selected=\"false\">Albums</button> <button type=\"button\" class=\"tab tab-lifted px-4 py-2\" data-tab=\"artists\" role=\"tab\" aria-selected=\"false\">Artists</button></div><div class=\"text-sm text-base-content/70\"><span id=\"results-count\">0</span> results</div></div><div class=\"space-y-4\"><div class=\"flex items-center justify-between\"><h2 id=\"results-heading\" class=\"text-xl font-semibold\">Tracks</h2><span class=\"badge badge-outline\" id=\"active-filters\" hidden>Filters active</span></div><div id=\"results-container\" class=\"grid gap-4\" role=\"tabpanel\" aria-live=\"polite\"></div><div id=\"empty-state\" class=\"hidden rounded-box border border-dashed border-base-300 bg-base-100/70 p-10 text-center\"><h3 class=\"text-lg font-semibold\">No matches yet</h3><p class=\"mt-2 text-base-content/70\">Try adjusting your search or removing filters to see more songs.</p></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout(PageMeta{
			Title:       "Lyric · Search",
			Description: "Search worship tracks, albums, and artists to build your next set list in seconds.",
			Path:        "/search",
			Canonical:   "https://lyric.app/search",
			ActiveNav:   "search",
			MainClass:   "mx-auto flex w-full max-w-6xl flex-1 flex-col gap-12 px-6 py-12",
			OGImage:     "/static/opengraph/search.png",
			SchemaJSON:  SearchResultsSchema("Lyric Search", "Search worship charts, albums, and artists curated for your team.", "https://lyric.app/search"),
			BodyScripts: BodyScripts(
				JSONScript("search-data", searchPayloadJSON()),
				InlineScript(searchClientScript()),
			),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
