root = ""
tmp_dir = ".air"

testdata_dir = "testdata"

[build]
  cmd = "go build -o .air/api ./cmd/api"
  bin = ".air/api"
  include_ext = ["go"]
  include_dir = ["cmd", "internal"]
  exclude_dir = [".git", "node_modules", "static", "db", ".gocache", ".air"]
  stop_on_error = true

[log]
  time = true

[runner]
  cmd = ".air/api"
  env = ["GOCACHE=.gocache"]
  restart = "always"
